CREATE TABLE directory_sizes (
    id INT IDENTITY(1,1) PRIMARY KEY,
    hostname VARCHAR(255),
    app_name VARCHAR(255),
    sub_app_name VARCHAR(255),
    path VARCHAR(255),
    size BIGINT,
    used_space FLOAT,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

def save_to_db(results):
    conn = pyodbc.connect(Constants.Connection)
    cursor = conn.cursor()

    try:
        for result in results:
            app_name, sub_app_name, path, size, used_space = result
            cursor.execute('''INSERT INTO directory_sizes (hostname, app_name, sub_app_name, path, size, used_space, last_updated)
                              VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP)''', (hostname, app_name, sub_app_name, path, size, used_space))
        conn.commit()
        print("Data inserted successfully.")
    except pyodbc.Error as e:
        print("Data insertion failed:", e)
    finally:
        conn.close()
